controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_controller:
      type: position_controllers/JointGroupPositionController

    traction_controller:
      type: velocity_controllers/JointGroupVelocityController

    piper_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

steering_controller:
  ros__parameters:
    joints:
      - fl_steering_joint
      - fr_steering_joint
      - rl_steering_joint
      - rr_steering_joint

traction_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint

piper_arm_controller:
  ros__parameters:
    joints:
      - piper_joint1
      - piper_joint2
      - piper_joint3
      - piper_joint4
      - piper_joint5
      - piper_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
